USE [master]
GO

/****** Object:  Database [FoodFast]    Script Date: 16-3-2018 09:55:03 ******/
CREATE DATABASE [FoodFast]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FoodFast', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\FoodFast.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FoodFast_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\FoodFast_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FoodFast] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FoodFast].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FoodFast] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FoodFast] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FoodFast] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FoodFast] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FoodFast] SET ARITHABORT OFF 
GO

ALTER DATABASE [FoodFast] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FoodFast] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FoodFast] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FoodFast] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FoodFast] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FoodFast] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FoodFast] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FoodFast] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FoodFast] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FoodFast] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FoodFast] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FoodFast] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FoodFast] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FoodFast] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FoodFast] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FoodFast] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FoodFast] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FoodFast] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FoodFast] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FoodFast] SET  MULTI_USER 
GO

ALTER DATABASE [FoodFast] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FoodFast] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FoodFast] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FoodFast] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FoodFast] SET  READ_WRITE 
GO

